# fly.toml app configuration file generated for fox-book on 2023-12-28T14:55:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fox-book"
primary_region = "cdg"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"
  SECRET_KEY='*[R\n\\z\n0kGBpa8?n\t:>n[<34_\x0cqu^a6@A.ohx|jMQEG\x0c49d3E_H;D4*{E|I.'

  DATABASE_URL='postgres://fox_book:xvZM7bmDC6z7p8g@foxbookdb.flycast:5432/fox_book'

  EMAIL_HOST='smtp.gmail.com'
  EMAIL_HOST_USER='jobee.bestcompany@gmail.com'
  DEFAULT_FROM_EMAIL='jobee.bestcompany@gmail.com'
  EMAIL_HOST_PASSWORD='duuujraacgvzlfou'
  EMAIL_PORT=587

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
