# Generated by Django 4.2.8 on 2023-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('annotation', models.TextField(null=True)),
                ('cover', models.URLField(null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
