# Generated by Django 4.2.8 on 2023-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Українська література', 'Українська література'), ('Зарубіжна література', 'Зарубіжна література')], max_length=255),
        ),
    ]
