# Generated by Django 4.2.7 on 2023-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
