# Generated by Django 4.2.8 on 2023-12-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='genre',
        ),
    ]
