# Generated by Django 4.2.8 on 2023-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_readingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsettings',
            name='bg_color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='readingsettings',
            name='text_color',
            field=models.CharField(max_length=255),
        ),
    ]
