# Generated by Django 4.2.8 on 2023-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_readingsettings_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='reading_progress',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
