# Generated by Django 4.2.8 on 2023-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_library_reading_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1, max_digits=3, null=True),
        ),
    ]
