# Generated by Django 4.2.8 on 2023-12-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_library_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
